version: "3.0"
services:
  postgres:
    build: .
    container_name: psql
    environment:
      POSTGRES_DB: "gsstore"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"